/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.frontend;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Hazem
 */
public class MainPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    /**
     * Creates new form MainPanel
     */
    public MainPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        BtnSignup = new javax.swing.JButton();

        setBackground(new java.awt.Color(17, 17, 17));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        BtnLogin.setBackground(new java.awt.Color(255, 255, 255));
        BtnLogin.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(51, 51, 51));
        BtnLogin.setText("Login");
        BtnLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLoginMouseExited(evt);
            }
        });
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        BtnSignup.setBackground(new java.awt.Color(255, 255, 255));
        BtnSignup.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        BtnSignup.setForeground(new java.awt.Color(0, 0, 0));
        BtnSignup.setText("Signup");
        BtnSignup.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnSignupMouseExited(evt);
            }
        });
        BtnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(logo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logo)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseEntered
        // TODO add your handling code here:
        BtnLogin.setBorder(BorderFactory.createLineBorder(Color.MAGENTA, 3));
    }//GEN-LAST:event_BtnLoginMouseEntered

    private void BtnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseExited
        // TODO add your handling code here:
        BtnLogin.setBorder(BorderFactory.createLineBorder(Color.WHITE, 3));
    }//GEN-LAST:event_BtnLoginMouseExited

    private void BtnSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSignupMouseEntered
        // TODO add your handling code here:
        BtnSignup.setBorder(BorderFactory.createLineBorder(Color.MAGENTA, 3));
    }//GEN-LAST:event_BtnSignupMouseEntered

    private void BtnSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSignupMouseExited
        // TODO add your handling code here:
        BtnSignup.setBorder(BorderFactory.createLineBorder(Color.WHITE, 3));
    }//GEN-LAST:event_BtnSignupMouseExited

    private void BtnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignupActionPerformed
        // TODO add your handling code here:
        mainFrame.getCardLayout().show(mainFrame.getContentPane(),"signup");
    }//GEN-LAST:event_BtnSignupActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        // TODO add your handling code here:
        mainFrame.getCardLayout().show(mainFrame.getContentPane(),"signup");
    }//GEN-LAST:event_BtnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton BtnSignup;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
