/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frontend;

import com.mycompany.CourseManagement.CourseServices;
import com.mycompany.UserAccountManagement.UserServices;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hazem
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private CardLayout cardLayout;
    private JPanel loginPanel;
    private JPanel signupPanel;
    private JPanel studentPanel;
    private JPanel instructorPanel;
    private JPanel mainPanel;
    private UserServices userServices;
    private CourseServices courseServices;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame(UserServices userServices, CourseServices courseServices) {
        this.userServices = userServices;
        this.courseServices = courseServices;
        setTitle("SkillForge Platform🔨");
        setSize(1280, 720); 
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cardLayout = new CardLayout();
        setLayout(cardLayout);
        setBackground(Color.white);
        initComponents(); 
        
        mainPanel = new MainPanel(this);
        add(mainPanel,"home");
        
//        loginPanel = new LoginPanel(this);
//        add(loginPanel,"login");
//        
//        signupPanel = new SignupPanel(this);
//        add(signupPanel, "signup");
//        
//        instructorPanel = new InstructorPanel(this);
//        add(instructorPanel,"instructor");
//        
//        studentPanel = new StudentPanel(this);
//        add(studentPanel,"student");
        
        cardLayout.show(getContentPane(),"home");
        setVisible(true);
        
//        loginPanel = new LoginPanel(this);
//        mainPanel.add(loginPanel,"login");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UserServices userServices;
        CourseServices courseServices;
        try
        {
            userServices = new UserServices();
            courseServices = new CourseServices();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame(userServices,courseServices).setVisible(true));
    }

    public UserServices getUserServices() {
        return userServices;
    }

    public void setUserServices(UserServices userServices) {
        this.userServices = userServices;
    }

    public CourseServices getCourseServices() {
        return courseServices;
    }

    public void setCourseServices(CourseServices courseServices) {
        this.courseServices = courseServices;
    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }

    public JPanel getLoginPanel() {
        return loginPanel;
    }

    public JPanel getSignupPanel() {
        return signupPanel;
    }

    public JPanel getStudentPanel() {
        return studentPanel;
    }

    public JPanel getInstructorPanel() {
        return instructorPanel;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
