/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.frontend.Main;

import com.mycompany.InputVerifiers.IsEmptyVerifier;
import com.mycompany.UserAccountManagement.User;
import com.mycompany.UserAccountManagement.UserServices;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Hazem
 */
public class LoginPanel extends javax.swing.JPanel {

    private final MainFrame mainFrame;
    private final IsEmptyVerifier userIdVerifier = new IsEmptyVerifier("User ID");
    private final IsEmptyVerifier passwordVerifier = new IsEmptyVerifier("Password");

    /**
     * Creates new form LoginPanel
     * 
     * @param mainFrame
     */
    public LoginPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        fieldUserId.setInputVerifier(userIdVerifier);
        fieldPassword.setInputVerifier(passwordVerifier);
        btnBack.setVerifyInputWhenFocusTarget(false);
        btnLogin.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnBack = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        labelUserId = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        fieldUserId = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(854, 533));
        setPreferredSize(new java.awt.Dimension(854, 533));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridBagLayout());

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnBack.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setAlignmentX(0.2F);
        btnBack.setBorder(null);
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.ipady = -15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        add(btnBack, gridBagConstraints);

        labelTitle.setBackground(new java.awt.Color(207, 207, 225));
        labelTitle.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("L o g i n   P a g e");
        labelTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null,
                null, java.awt.Color.darkGray, java.awt.Color.gray));
        labelTitle.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 38, 0, 0);
        add(labelTitle, gridBagConstraints);

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.setOpaque(true);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 747;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(77, 6, 0, 0);
        add(btnLogin, gridBagConstraints);

        labelUserId.setBackground(new java.awt.Color(255, 255, 255));
        labelUserId.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelUserId.setForeground(new java.awt.Color(0, 0, 0));
        labelUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUserId.setText("User ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 473;
        gridBagConstraints.ipady = -8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(99, 100, 0, 0);
        add(labelUserId, gridBagConstraints);

        labelPassword.setBackground(new java.awt.Color(255, 255, 255));
        labelPassword.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(0, 0, 0));
        labelPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 430;
        gridBagConstraints.ipady = -18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(92, 110, 0, 0);
        add(labelPassword, gridBagConstraints);

        fieldUserId.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fieldUserId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldUserId.setMaximumSize(new java.awt.Dimension(68, 58));
        fieldUserId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldUserIdFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldUserIdFocusLost(evt);
            }
        });
        fieldUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUserIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 493;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(89, 140, 0, 0);
        add(fieldUserId, gridBagConstraints);

        fieldPassword.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fieldPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldPassword.setMaximumSize(new java.awt.Dimension(68, 58));
        fieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldPasswordFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 493;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(82, 140, 0, 0);
        add(fieldPassword, gridBagConstraints);

        background.setBackground(new java.awt.Color(207, 207, 225));
        background.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.ipadx = 860;
        gridBagConstraints.ipady = 540;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(background, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLoginActionPerformed
        if (userIdVerifier.verify(fieldUserId) && passwordVerifier.verify(fieldPassword)) {
            try {
                User user = UserServices.login(fieldUserId.getText(), String.valueOf(fieldPassword.getPassword()));
                if (user == null) {
                    JOptionPane.showMessageDialog(this, "Invalid Credentials", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    this.mainFrame.navigateToUserFrame(user);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }// GEN-LAST:event_btnLoginActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        showHome();
    }// GEN-LAST:event_btnBackActionPerformed

    private void fieldUserIdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fieldUserIdActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_fieldUserIdActionPerformed

    private void fieldUserIdFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_fieldUserIdFocusGained
        // TODO add your handling code here:
        labelUserId.setVisible(false);
    }// GEN-LAST:event_fieldUserIdFocusGained

    private void fieldUserIdFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_fieldUserIdFocusLost
        // TODO add your handling code here:
    }// GEN-LAST:event_fieldUserIdFocusLost

    private void fieldPasswordFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_fieldPasswordFocusGained
        // TODO add your handling code here:
        labelPassword.setVisible(false);
    }// GEN-LAST:event_fieldPasswordFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUserId;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelUserId;

    // End of variables declaration//GEN-END:variables
    public final void showHome() {
        mainFrame.getCardLayout().show(mainFrame.getContentPane(), "home");
    }

    public void refreshFields() {
        this.fieldUserId.setText("");
        this.fieldPassword.setText("");
    }
}
