/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frontend.Main;

import com.mycompany.UserAccountManagement.Admin;
import com.mycompany.UserAccountManagement.Instructor;
import com.mycompany.UserAccountManagement.Student;
import com.mycompany.UserAccountManagement.User;
import com.mycompany.frontend.AdminDashboard.AdminDashboardFrame;
import com.mycompany.frontend.InstructorDashboard.InstructorDashboardFrame;
import com.mycompany.frontend.StudentDashboard.StudentDashboardFrame;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author Hazem
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MainFrame.class.getName());
    private CardLayout cardLayout;
    private LoginPanel loginPanel;
    private SignupPanel signupPanel;
    private MainPanel mainPanel;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {

        setTitle("SkillForge Platform");
        setSize(1280, 720);
        setMinimumSize(new Dimension(1280, 720));
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cardLayout = new CardLayout();
        setLayout(cardLayout);
        setBackground(Color.white);
        initComponents();

        mainPanel = new MainPanel(this);
        add(mainPanel, "home");

        loginPanel = new LoginPanel(this);
        add(loginPanel, "login");

        signupPanel = new SignupPanel(this);
        add(signupPanel, "signup");

        cardLayout.show(getContentPane(), "home");
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        // ===== Sample quiz initialization disabled - instructors create their own
        // quizzes =====
        // try {
        // QuizDataInitializer.initializeSampleQuizzes();
        // } catch (Exception e) {
        // System.out.println("Error initializing sample quizzes: " + e.getMessage());
        // }
        // ===========================

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }

    public LoginPanel getLoginPanel() {
        return loginPanel;
    }

    public SignupPanel getSignupPanel() {
        return signupPanel;
    }

    public MainPanel getMainPanel() {
        return mainPanel;
    }

    public void navigateToUserFrame(User user) {
        if (user instanceof Instructor) {
            InstructorDashboardFrame instructorDashboardFrame = new InstructorDashboardFrame((Instructor) user);
            instructorDashboardFrame.setVisible(true);
        } else if (user instanceof Student) {
            StudentDashboardFrame studentDashboardFrame = new StudentDashboardFrame((Student) user);
            studentDashboardFrame.setVisible(true);
        } else if (user instanceof Admin) {
            AdminDashboardFrame adminDashboardFrame = new AdminDashboardFrame();
            adminDashboardFrame.setVisible(true);
        }
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
