/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.frontend.InstructorDashboard;

/**
 *
 * @author Zeyad
 */
public class CourseCard extends javax.swing.JPanel {

    /**
     * Creates new form CourseCard
     */
    public CourseCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxPanel = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        boxPanel.setLayout(new javax.swing.BoxLayout(boxPanel, javax.swing.BoxLayout.Y_AXIS));

        // Set alignment for full width
        jLabelTitle.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        jLabelDescription.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        // Add components in order
        boxPanel.add(jLabelTitle);
        boxPanel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 8)));
        boxPanel.add(jLabelDescription);

        // Set panel properties
        boxPanel.setPreferredSize(new java.awt.Dimension(300, 150));
        boxPanel.setMaximumSize(new java.awt.Dimension(300, java.lang.Integer.MAX_VALUE));
        boxPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        boxPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boxPanel.setLayout(new javax.swing.BoxLayout(boxPanel, javax.swing.BoxLayout.Y_AXIS));

        jLabelTitle.setText("jLabel1");
        boxPanel.add(jLabelTitle);

        jLabelDescription.setText("jLabel1");
        boxPanel.add(jLabelDescription);

        add(boxPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxPanel;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables

    // Methods to set course data
    public void setCourseTitle(String title) {
        jLabelTitle.setText(title);
    }

    public void setCourseDescription(String description) {
        jLabelDescription.setText(description);
    }

    public void setCourseData(String title, String description) {
        jLabelTitle.setText(title);
        jLabelDescription.setText(description);
    }
}
