/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frontend.InstructorDashboard;

import com.mycompany.CourseManagement.Course;
import com.mycompany.CourseManagement.Lesson;
import com.mycompany.UserAccountManagement.Instructor;
import java.awt.CardLayout;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class InstructorDashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form InstructorDashboardFrame
     */
    CardLayout cardLayout;
    JPanel cardsPanel;
    private Instructor instructor;

    public InstructorDashboardFrame(Instructor instructor) {
        this.instructor = instructor;
        initComponents();
        cardLayout = new CardLayout();
        cardsPanel = new JPanel(cardLayout);
        getContentPane().add(cardsPanel);
        showDashboard();
    }

    public InstructorDashboardFrame() {
        try {
            this.instructor = new Instructor("instructor1", "Default Instructor", "instructor@example.com", "password");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error initializing instructor: " + ex.getMessage());
        }
        initComponents();
        cardLayout = new CardLayout();
        cardsPanel = new JPanel(cardLayout);
        getContentPane().add(cardsPanel);
        showDashboard();
    }

    public void showDashboard() {
        DashboardPanel dashboard = new DashboardPanel(this, instructor);

        cardsPanel.add(dashboard, "DASHBOARD");

        cardLayout.show(cardsPanel, "DASHBOARD");
    }

    public void showCourseView(Course course) {
        CourseView cv = new CourseView(this, course, instructor);

        cardsPanel.add(cv, "COURSEVIEW");

        cardLayout.show(cardsPanel, "COURSEVIEW");
    }

    public void showLessonPanel(Lesson lesson, Course course) {
        LessonPanel lp = new LessonPanel(this, lesson, course, instructor);

        cardsPanel.add(lp, "LESSON");

        cardLayout.show(cardsPanel, "LESSON");
    }

    public void showCourseFormPanel(Course course) {
        CourseFormPanel cfp = new CourseFormPanel(this, instructor, course);

        cardsPanel.add(cfp, "COURSEFORM");

        cardLayout.show(cardsPanel, "COURSEFORM");
    }

    public void showLessonFormPanel(Course course, Lesson lesson) {
        LessonFormPanel lfp = new LessonFormPanel(this, instructor, course, lesson);

        cardsPanel.add(lfp, "LESSONFORM");

        cardLayout.show(cardsPanel, "LESSONFORM");
    }

    public void showCourseAnalytics(String courseId) {
        com.mycompany.frontend.Charts.CourseAnalyticsPanel cap = new com.mycompany.frontend.Charts.CourseAnalyticsPanel(
                this, courseId);

        cardsPanel.add(cap, "COURSEANALYTICS");

        cardLayout.show(cardsPanel, "COURSEANALYTICS");
    }

    public void showLessonAnalytics(String courseId, String lessonId) {
        com.mycompany.frontend.Charts.LessonAnalyticsPanel lap = new com.mycompany.frontend.Charts.LessonAnalyticsPanel(
                this, courseId, lessonId);

        cardsPanel.add(lap, "LESSONANALYTICS");

        cardLayout.show(cardsPanel, "LESSONANALYTICS");
    }

    public void showStudentPerformance(String studentId, String courseId) {
        com.mycompany.frontend.Charts.StudentPerformancePanel spp = new com.mycompany.frontend.Charts.StudentPerformancePanel(
                this, studentId, courseId);

        cardsPanel.add(spp, "STUDENTPERFORMANCE");

        cardLayout.show(cardsPanel, "STUDENTPERFORMANCE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(900, 600);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
